language: objective-c

osx_image: xcode8

env:
  - SCHEME=UpholdSdk
  - SCHEME=UpholdSdkSandbox

before_script:
  - brew update
  - carthage update --platform iOS

script:
  - swiftlint lint --strict
  - xcodebuild -project UpholdSdk.xcodeproj test -scheme $SCHEME -sdk iphonesimulator -destination "name=iPhone SE" | xcpretty
